# Generated by Django 3.2.9 on 2022-01-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMPANY_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_id', models.CharField(max_length=10)),
                ('D_id', models.CharField(max_length=10)),
                ('co_name', models.CharField(max_length=20)),
                ('li_no', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'COMPANY_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='CONTRACTOR_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contractor_id', models.CharField(max_length=10)),
                ('D_id', models.CharField(max_length=10)),
                ('con_name', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=20)),
                ('Field_of_work', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=20)),
                ('lic_no', models.CharField(max_length=20)),
                ('W_img', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CONTRACTOR_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='CUSTOMER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=10)),
                ('D_id', models.CharField(max_length=10)),
                ('cu_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CUSTOMER_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Ph_no', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
                ('type_id', models.CharField(max_length=10)),
                ('Rating', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'DETAILS',
            },
        ),
        migrations.CreateModel(
            name='idgenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.IntegerField()),
                ('coid', models.IntegerField()),
                ('wid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('rid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('did', models.IntegerField()),
            ],
            options={
                'db_table': 'idgenerator',
            },
        ),
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'LOGIN',
            },
        ),
        migrations.CreateModel(
            name='RATES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate_id', models.CharField(max_length=10)),
                ('Type_of_work', models.CharField(max_length=10)),
                ('Type_id', models.CharField(max_length=20)),
                ('Rate', models.IntegerField()),
                ('M_name', models.CharField(max_length=10)),
                ('M_Rate', models.IntegerField()),
            ],
            options={
                'db_table': 'RATES',
            },
        ),
        migrations.CreateModel(
            name='SHOP_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_id', models.CharField(max_length=10)),
                ('Shop_name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Ph_no', models.CharField(max_length=10)),
                ('Mname', models.CharField(max_length=20)),
                ('Type_id', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'SHOP_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='TYPE_OF_WORK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_id', models.CharField(max_length=10)),
                ('Type_of_work', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TYPE_OF_WORK',
            },
        ),
        migrations.CreateModel(
            name='WORKER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_id', models.CharField(max_length=10)),
                ('D_id', models.CharField(max_length=10)),
                ('W_name', models.CharField(max_length=20)),
                ('Fd_of_work', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=20)),
                ('U_name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'WORKER_DETAILS',
            },
        ),
    ]
