# Generated by Django 3.2.9 on 2022-01-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220118_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor_details',
            name='con_name',
        ),
    ]
