# Generated by Django 3.2.9 on 2022-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contractor_details_con_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contractor_details',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
