# Generated by Django 3.2.9 on 2022-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220119_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor_details',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor_details',
            name='months',
            field=models.CharField(default='o', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor_details',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_details',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_details',
            name='months',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_details',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
