# Generated by Django 3.2.9 on 2022-02-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220130_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='Type_of_work',
        ),
    ]
