# Generated by Django 3.2.9 on 2022-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rates_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='Rate_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
