# Generated by Django 3.2.9 on 2022-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rates_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
