# Generated by Django 3.2.9 on 2022-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_details_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_details',
            name='Mname',
        ),
        migrations.AddField(
            model_name='shop_details',
            name='City',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
