# Generated by Django 3.2.9 on 2022-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220220_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_details',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
