# Generated by Django 3.2.9 on 2022-02-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_shop_details_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='Unit',
        ),
    ]
