# Generated by Django 3.2.9 on 2022-02-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220226_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='username',
            new_name='userid',
        ),
    ]
