# Generated by Django 3.2.9 on 2022-02-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_username_photos_userid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photos',
            table='Photos',
        ),
    ]
