# Generated by Django 3.2.9 on 2022-02-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_photos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photos',
            table='PHOTOS',
        ),
    ]
