# Generated by Django 3.2.9 on 2022-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='user_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
