# Generated by Django 3.2.9 on 2022-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_photos_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MESSAGES',
            },
        ),
    ]
