# Generated by Django 3.2.9 on 2022-02-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_details',
            name='profile',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
