# Generated by Django 3.2.9 on 2022-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_worker_details_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROFILES',
            },
        ),
    ]
