# Generated by Django 3.2.9 on 2022-06-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor_details',
            name='W_img',
        ),
        migrations.AddField(
            model_name='worker_details',
            name='profile_image',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
