# Generated by Django 3.2.9 on 2022-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220613_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Desc', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=30)),
                ('Worker_id', models.CharField(max_length=20)),
                ('Customer_id', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'WORK_INVITE',
            },
        ),
    ]
