# Generated by Django 3.2.9 on 2022-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_materials_quotation_invite_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='M_name',
            field=models.CharField(max_length=50),
        ),
    ]
