# Generated by Django 3.2.9 on 2022-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_rates_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='M_name',
            field=models.CharField(max_length=50),
        ),
    ]
