# Generated by Django 3.2.9 on 2022-06-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_materials_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor_details',
            name='profile_image',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
