# Generated by Django 3.2.9 on 2022-06-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_contractor_details_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotation_invite',
        ),
    ]
