# Generated by Django 3.2.9 on 2022-06-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220622_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_projects',
        ),
    ]
