# Generated by Django 3.2.9 on 2022-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_tbl_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=20)),
                ('p_name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('D_start', models.DateField()),
                ('D_end', models.DateField()),
                ('lat', models.FloatField(max_length=50)),
                ('lon', models.FloatField(max_length=50)),
                ('Loc', models.CharField(max_length=30)),
                ('Plan_img', models.CharField(max_length=100)),
                ('Suggestion', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_projects',
            },
        ),
    ]
