# Generated by Django 3.2.9 on 2022-06-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_tbl_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contractor_invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_id', models.CharField(max_length=5)),
                ('Contractor_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_contractor_invite',
            },
        ),
    ]
