# Generated by Django 3.2.9 on 2022-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_contractor_details_p_sts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgenerator',
            name='pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_contractor_invite',
            name='cinvite_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
