# Generated by Django 3.2.9 on 2022-06-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_tbl_contractor_invite_cinvite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='M_Rate',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='M_name',
        ),
    ]
