# Generated by Django 3.2.9 on 2022-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20220701_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_id', models.CharField(max_length=5)),
                ('Contractor_id', models.CharField(max_length=10)),
                ('Customer_id', models.CharField(max_length=10)),
                ('amt', models.IntegerField()),
                ('file', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_quotation',
            },
        ),
    ]
