# Generated by Django 3.2.9 on 2022-07-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_tbl_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_id', models.CharField(max_length=5)),
                ('Contractor_id', models.CharField(max_length=10)),
                ('Customer_id', models.CharField(max_length=10)),
                ('ramt', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_payment_request',
            },
        ),
        migrations.CreateModel(
            name='tbl_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpayment_id', models.CharField(max_length=10)),
                ('payment_id', models.CharField(max_length=10)),
                ('pamount', models.IntegerField()),
                ('bamount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_payments',
            },
        ),
    ]
