# Generated by Django 3.2.9 on 2022-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_tbl_payment_request_tbl_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
