# Generated by Django 3.2.9 on 2022-07-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_tbl_payments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payments',
            name='bamount',
            field=models.IntegerField(default=0),
        ),
    ]
