# Generated by Django 3.2.9 on 2022-07-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_tbl_progress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_progress',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
