# Generated by Django 3.2.9 on 2022-07-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_tbl_progress_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=10)),
                ('to_id', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_rating',
            },
        ),
    ]
