# Generated by Django 3.2.9 on 2022-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rating',
            name='project_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
